---
    - name: add user to sshd AllowUsers
      hosts: all
      gather_facts: no
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        backup: true
        backrefs: true
        regex: "^AllowUsers\\s+(.*)$"
        line: "AllowUsers \\1 {{ var_user }}"
        state: present
        validate: sshd -t -f %s
      when:
        - grep_allowusers.rc == 1
      notify:
        - "reload_sshd"
    - name: reload sshd
      service:
        name: sshd
        state: reloaded
