---
- name: Create User
  gather_facts: no
  hosts: all
  became: yes
  vars:
    ansible_become: true
    ansible_become_method: sudo
  tasks:
    - name: Add the user and Password , Assign to Group 
      user:
        name: '{{ var_user }}'
        group: '{{ var_group }}'
        password: '{{ var_password }}'
        state: present
